<?php

namespace FormationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EtudiantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantsRepository extends EntityRepository
{
}
